/**
 * スキル生成テンプレート (#57)
 *
 * 機能:
 * - スキルひな形生成機能
 * - SKILL.md / package.json / index.js 自動生成
 * - 必須フィールドのプレースホルダー
 */

import * as fs from 'fs';
import * as path from 'path';

export interface SkillConfig {
  name: string;
  description: string;
  features: string[];
  author?: string;
  version?: string;
  dependencies?: string[];
  hasCron?: boolean;
  hasConfig?: boolean;
}

export interface GeneratedSkill {
  path: string;
  files: string[];
}

export class SkillGenerator {
  private skillsDir: string;

  constructor(skillsDir: string) {
    this.skillsDir = skillsDir;
  }

  /**
   * スキルを生成
   */
  async generate(config: SkillConfig): Promise<GeneratedSkill> {
    const skillPath = path.join(this.skillsDir, config.name);
    const files: string[] = [];

    // ディレクトリ作成
    if (!fs.existsSync(skillPath)) {
      fs.mkdirSync(skillPath, { recursive: true });
    }

    // SKILL.md生成
    const skillMd = this.generateSkillMd(config);
    const skillMdPath = path.join(skillPath, 'SKILL.md');
    fs.writeFileSync(skillMdPath, skillMd, 'utf-8');
    files.push('SKILL.md');

    // package.json生成
    const packageJson = this.generatePackageJson(config);
    const packageJsonPath = path.join(skillPath, 'package.json');
    fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2), 'utf-8');
    files.push('package.json');

    // index.ts生成
    const indexTs = this.generateIndexTs(config);
    const indexTsPath = path.join(skillPath, 'index.ts');
    fs.writeFileSync(indexTsPath, indexTs, 'utf-8');
    files.push('index.ts');

    // config.json生成（オプション）
    if (config.hasConfig) {
      const configJson = this.generateConfigJson(config);
      const configJsonPath = path.join(skillPath, 'config.json');
      fs.writeFileSync(configJsonPath, JSON.stringify(configJson, null, 2), 'utf-8');
      files.push('config.json');
    }

    // cron.json生成（オプション）
    if (config.hasCron) {
      const cronJson = this.generateCronJson(config);
      const cronJsonPath = path.join(skillPath, 'cron.json');
      fs.writeFileSync(cronJsonPath, JSON.stringify(cronJson, null, 2), 'utf-8');
      files.push('cron.json');
    }

    return {
      path: skillPath,
      files,
    };
  }

  /**
   * SKILL.mdテンプレートを生成
   */
  private generateSkillMd(config: SkillConfig): string {
    return `# ${config.name}

${config.description}

## 機能

${config.features.map(f => `- ${f}`).join('\n')}

## 依存関係

${config.dependencies && config.dependencies.length > 0
  ? config.dependencies.map(d => `- ${d}`).join('\n')
  : 'なし'}

## 設定

${config.hasConfig ? '`config.json` で設定を管理します。' : '設定は不要です。'}

## 使用方法

\`\`\`typescript
import { ${this.toPascalCase(config.name)} } from './index';

const skill = new ${this.toPascalCase(config.name)}();
await skill.run();
\`\`\`

## 注意事項

- [ ] TODO: 必要に応じて設定を更新してください
- [ ] TODO: cronスケジュールを調整してください

---

*Generated by autonomous-proposal skill on ${new Date().toISOString()}*
`;
  }

  /**
   * package.jsonテンプレートを生成
   */
  private generatePackageJson(config: SkillConfig): any {
    return {
      name: config.name,
      version: config.version || '1.0.0',
      description: config.description,
      main: 'dist/index.js',
      types: 'dist/index.d.ts',
      scripts: {
        build: 'tsc',
        test: 'node --experimental-vm-modules node_modules/jest/bin/jest.js',
        lint: 'eslint src/**/*.ts',
      },
      keywords: [
        'openclaw',
        'skill',
        'automation',
        ...config.features.slice(0, 3),
      ],
      author: config.author || 'Kanna',
      license: 'MIT',
      devDependencies: {
        '@types/node': '^22.0.0',
        typescript: '^5.3.0',
        jest: '^29.7.0',
        '@types/jest': '^29.5.0',
        'ts-jest': '^29.1.0',
      },
      dependencies: {},
    };
  }

  /**
   * index.tsテンプレートを生成
   */
  private generateIndexTs(config: SkillConfig): string {
    const className = this.toPascalCase(config.name);

    return `/**
 * ${config.name}
 *
 * ${config.description}
 */

export class ${className} {
  private config: any;

  constructor(config?: any) {
    this.config = config || {};
  }

  /**
   * メイン実行メソッド
   */
  async run(): Promise<void> {
    console.log('${config.name} started');

    // TODO: メインロジックを実装

    console.log('${config.name} completed');
  }

  /**
   * 設定を更新
   */
  updateConfig(config: any): void {
    this.config = { ...this.config, ...config };
  }
}

export default ${className};
`;
  }

  /**
   * config.jsonテンプレートを生成
   */
  private generateConfigJson(config: SkillConfig): any {
    return {
      enabled: true,
      schedule: '0 9 * * *', // デフォルト: 毎日9時
      options: {
        // TODO: スキル固有の設定を追加
      },
    };
  }

  /**
   * cron.jsonテンプレートを生成
   */
  private generateCronJson(config: SkillConfig): any {
    return {
      jobs: [
        {
          name: `${config.name}-daily`,
          schedule: '0 9 * * *',
          enabled: true,
        },
      ],
    };
  }

  /**
   * ケバブケースをパスカルケースに変換
   */
  private toPascalCase(str: string): string {
    return str
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
  }

  /**
   * 既存のスキルをベースに新しいスキルを生成
   */
  async generateFromTemplate(
    templateName: string,
    newConfig: Partial<SkillConfig>
  ): Promise<GeneratedSkill> {
    // テンプレートスキルのパス
    const templatePath = path.join(this.skillsDir, templateName);

    if (!fs.existsSync(templatePath)) {
      throw new Error(`Template skill "${templateName}" not found`);
    }

    // テンプレートの設定を読み込み
    const templateConfig = await this.loadTemplateConfig(templatePath);

    // 新しい設定とマージ
    const config: SkillConfig = {
      ...templateConfig,
      ...newConfig,
      name: newConfig.name || templateConfig.name,
    };

    return this.generate(config);
  }

  /**
   * テンプレート設定を読み込み
   */
  private async loadTemplateConfig(templatePath: string): Promise<SkillConfig> {
    const skillMdPath = path.join(templatePath, 'SKILL.md');

    if (!fs.existsSync(skillMdPath)) {
      throw new Error('SKILL.md not found in template');
    }

    const content = fs.readFileSync(skillMdPath, 'utf-8');
    const lines = content.split('\n');

    // タイトルを抽出
    const titleMatch = lines[0].match(/^#\s+(.+)$/);
    const name = titleMatch ? titleMatch[1] : 'unknown-skill';

    // 説明を抽出（2行目〜最初の##まで）
    const descriptionLines: string[] = [];
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].startsWith('##')) break;
      if (lines[i].trim()) {
        descriptionLines.push(lines[i]);
      }
    }
    const description = descriptionLines.join(' ').trim();

    // 機能リストを抽出
    const features: string[] = [];
    let inFeaturesSection = false;
    for (const line of lines) {
      if (line.startsWith('## 機能')) {
        inFeaturesSection = true;
        continue;
      }
      if (line.startsWith('##')) {
        inFeaturesSection = false;
      }
      if (inFeaturesSection && line.startsWith('- ')) {
        features.push(line.substring(2));
      }
    }

    return {
      name,
      description,
      features,
    };
  }
}
